- name: WSUS ID cleanup
  hosts: all 
  vars:
    ansible_winrm_scheme: http
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: kerberos
  tasks:
  - name: Stop a service
    win_service:
     name: wuauserv
     state: stopped
  - name: Remove registry key PingID
    win_regedit:
     path: HKLM:\Software\Microsoft\Windows\CurrentVersion\WindowsUpdate
     name: PingID
     state: absent
     delete_key: yes
  - name: Remove registry key AccountDomainSid 
    win_regedit:
     path: HKLM:\Software\Microsoft\Windows\CurrentVersion\WindowsUpdate
     name: AccountDomainSid
     state: absent
     delete_key: yes
  - name: Remove registry key SusClientId
    win_regedit:
     path: HKLM:\Software\Microsoft\Windows\CurrentVersion\WindowsUpdate
     name: SusClientId
     state: absent
     delete_key: yes
  - name: Remove registry key SusClientIDValidation
    win_regedit:
     path: HKLM:\Software\Microsoft\Windows\CurrentVersion\WindowsUpdate
     name: SusClientIDValidation
     state: absent
     delete_key: yes
  - name: Start a service
    win_service:
     name: wuauserv
     state: started
  - name: reset windows update (pre 2016)
    win_shell: wuauclt /resetauthorization /detectnow /UpdateNow
    ignore_errors: yes
  - name: reset windows update (2016+)
    win_shell: usoclient.exe startscan 
    args:
     removes: c:\windows\system32\usoclient.exe
    ignore_errors: yes
